### ISSUE TITLE
nodegyp error in  windows 10 

### ISSUE THREAD

**Issue by devarajchidambaram** [bripkens/event-loop-stats#1]
When I was tried to install the event loop stats in Windows 10-pro environment,  below error is throwing
Previously I installed gc-stats npm with any problem.
My question is event loop stats supporting in windows10 environment?
help me to to fix the issue.
 
if not defined npm_config_node_gyp (node "C:\Users
\bane\AppData\Roaming\nvm\v6.11.2\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5):
 error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change
the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution"
. [C:\Users\bane\Desktop\logger\node_modules\event-loop-stats\build\eventLoopStats.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bane\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_mo
dules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bane\\AppData\\Roaming\\nvm\\v6.11.2\\node
_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bane\Desktop\logger\node_modules\event-loop-stats
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN logger@1.0.0 No description
npm WARN logger@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! event-loop-stats@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the event-loop-stats@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bane\AppData\Roaming\npm-cache\_logs\2017-10-05T10_19_15_714Z-debug.log

**Comment by devarajchidambaram** [comment]
Hi,

When I install eventloop stats In windows 10 pro environment, below error is throwing

C:\Users\devaraj\node_modules\event-loop-stats>if not
 defined npm_config_node_gyp (node "C:\Users\devaraj.c\AppData\Roaming\nvm\v6.11.2\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  eventLoopStats.cc
  win_delay_load_hook.cc
c:\users\devaraj.c\.node-gyp\6.11.2\include\node\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No
such file or directory (compiling source file ..\src\eventLoopStats.cc) [C:\Users\devaraj.c\OneDrive - Guidanz inc
\eg-node\EG\test\process_metrics\node_modules\event-loop-stats\build\eventLoopStats.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file C:\Users\devaraj.c\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\no
de-gyp\src\win_delay_load_hook.cc) [C:\Users\devaraj.c\OneDrive - Guidanz inc\eg-node\EG\test\process_metrics
\node_modules\event-loop-stats\build\eventLoopStats.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\devaraj.c\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\node-
gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\devaraj.c\\AppData\\Roaming\\nvm\\v6.11.2\\node_modules\\n
pm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\devaraj.c\OneDrive - Guidanz inc\eg-node\EG\test\process_metrics\node_modules\event-loop
-stats
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN process_metrics@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "event-loop-stats" "--save"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
